# Generated by Django 5.2.8 on 2025-11-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('category_tag', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, help_text="Capture d'écran du projet", null=True, upload_to='projects/')),
                ('result_text', models.CharField(help_text='Ex: 100% Sécurisé, -40% temps attente', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('CYBER', 'Cybersécurité'), ('DEV', 'Développement Digital')], max_length=5)),
                ('icon_name', models.CharField(help_text="Nom de l'icône Phosphor (ex: ph-shield)", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Co-Fondateur', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('certifications', models.CharField(blank=True, help_text='Ex: CEH, CISSP, AWS Certified', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
        ),
    ]
